using System;
using System.IO;
using System.Linq;
using UnityEngine;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine.SceneManagement;
using Ink.Runtime;
namespace AmoraNovel.Editor {
[InitializeOnLoad] public static class AmoraSetup {
 const string ScenePath="Assets/AmoraNovel/Amora.unity";
 static string CommandPath=>System.IO.Path.Combine(Directory.GetCurrentDirectory(),"Temp/amora-command.txt");
 static AmoraSetup(){EditorApplication.delayCall+=EnsureScene;EditorApplication.update+=Poll;}
 static T Asset<T>(string p)where T:UnityEngine.Object=>AssetDatabase.LoadAssetAtPath<T>("Assets/"+p);
 static void EnsureScene(){if(EditorApplication.isPlayingOrWillChangePlaymode||EditorApplication.isCompiling)return;if(!File.Exists(ScenePath))CreateScene();}
 [MenuItem("Amora/Create or open visual novel")]
 public static void CreateScene(){if(File.Exists(ScenePath)){EditorSceneManager.playModeStartScene=AssetDatabase.LoadAssetAtPath<SceneAsset>(ScenePath);return;}var previous=SceneManager.GetActiveScene();var scene=EditorSceneManager.NewScene(NewSceneSetup.EmptyScene,NewSceneMode.Additive);SceneManager.SetActiveScene(scene);var camera=new GameObject("Camera").AddComponent<Camera>();camera.backgroundColor=new Color(.15f,.04f,.12f);camera.clearFlags=CameraClearFlags.SolidColor;camera.gameObject.AddComponent<AudioListener>();var g=new GameObject("Amora • Visual Novel").AddComponent<AmoraGame>();
 g.ink=Asset<TextAsset>("Scripts/InkScript/CupidDialouge.ink.json");g.neutral=Asset<Texture2D>("Characters/Amora/amoraNeutral.png");g.blush=Asset<Texture2D>("Characters/Amora/amoraBlush.png");g.concerned=Asset<Texture2D>("Characters/Amora/amoraConcerned.png");g.angry=Asset<Texture2D>("Characters/Amora/amoraAngry.png");g.cupid=Asset<Texture2D>("Characters/Amora/amoraCupid.png");g.festival=Asset<Texture2D>("Backgrounds/GameJamBG1.png");g.cafe=Asset<Texture2D>("Backgrounds/GameJamBG2.png");g.heart=Asset<Texture2D>("Objects/Interface/Icons/pinkHeart.png");g.startArt=Asset<Texture2D>("Objects/Interface/Buttons/Start.png");g.universityMusic=Asset<AudioClip>("Music/tmrwagain.mp3");g.cafeMusic=Asset<AudioClip>("Music/whentimestoodstill.mp3");g.battleMusic=Asset<AudioClip>("Music/purgatory.mp3");g.titleMusic=Asset<AudioClip>("Music/willyoustaythenight.mp3");g.shotSound=Asset<AudioClip>("SFX/bulletsfx.mp3");
 EditorSceneManager.SaveScene(scene,ScenePath);EditorSceneManager.CloseScene(scene,true);SceneManager.SetActiveScene(previous);EditorSceneManager.playModeStartScene=AssetDatabase.LoadAssetAtPath<SceneAsset>(ScenePath);EditorBuildSettings.scenes=new[]{new EditorBuildSettingsScene(ScenePath,true)}.Concat(EditorBuildSettings.scenes.Where(x=>x.path!=ScenePath)).ToArray();Debug.Log("AMORA: Visual novel created. Press Play to begin. Existing scene remains intact.");}
 static void Poll(){if(EditorApplication.isCompiling||!File.Exists(CommandPath))return;string cmd;try{cmd=File.ReadAllText(CommandPath).Trim();File.Delete(CommandPath);}catch(IOException){return;}try{switch(cmd){case "test-story":TestStory();break;case "play":EditorSceneManager.playModeStartScene=AssetDatabase.LoadAssetAtPath<SceneAsset>(ScenePath);EditorApplication.isPlaying=true;break;case "stop":EditorApplication.isPlaying=false;break;case "test-runtime":RuntimeTests();break;case "show-battle":var g=AmoraGame.Instance;g.NewGame();g.SubmitName("Alex");SeekBattle(g);g.StartBattle();break;case "show-dialogue":var d=AmoraGame.Instance;d.NewGame();d.SubmitName("Alex");for(int i=0;i<15;i++)d.NextLine();break;case "title":AmoraGame.Instance.ShowTitle();break;case "build":Build();break;case "clear-test-save":File.Delete(System.IO.Path.Combine(Application.persistentDataPath,"amora-story.json"));break;}}catch(Exception e){Debug.LogException(e);File.WriteAllText("Temp/amora-test-error.txt",e.ToString());}}
 static void Assert(bool okay,string msg){if(!okay)throw new Exception(msg);}
 [MenuItem("Amora/Validate story routes")]
 public static void TestStory(){string json=Asset<TextAsset>("Scripts/InkScript/CupidDialouge.ink.json").text;var report=new System.Text.StringBuilder();
 for(int route=0;route<4;route++)for(int choice=0;choice<3;choice++){var s=new Story(json);s.variablesState["playerName"]="Alex";int battles1=0,battles2=0,lines=0,loops=0;bool named=false,complete=false;while(lines++<1800){if(s.canContinue){s.Continue();foreach(var tag in s.currentTags){if(tag=="SHOW_NAME_INPUT"){s.ChoosePathString("first_encounter");named=true;}if(tag=="event: unlock_festival")complete=true;if(tag=="effect: pink_flash")loops++;}continue;}if(s.currentChoices.Count==0)break;int selected=0;if(s.currentChoices.Any(x=>x.text=="Win")){bool first=s.state.currentPathString!=null&&s.state.currentPathString.Contains("test_bullethell"); // Use counters and first result variables: second encounter follows the token.
 first=!(bool)s.variablesState["heart_token"];
 bool win;if(first){battles1++;win=route==0||battles1>(route==1?1:2);}else{battles2++;win=route<2||battles2>(route==2?1:3);if(route==3&&loops>0){report.AppendLine("Rejection loop verified; authored fail count remains "+s.variablesState["second_fail_count"]);break;}}
 selected=s.currentChoices.FindIndex(x=>x.text==(win?"Win":"Lose"));}else if(s.currentChoices.Any(x=>x.text=="Try again"))selected=s.currentChoices.FindIndex(x=>x.text=="Try again");else if(s.currentChoices.Any(x=>x.text=="Yes"))selected=s.currentChoices.FindIndex(x=>x.text=="Yes");else selected=Mathf.Min(choice,s.currentChoices.Count-1);s.ChooseChoiceIndex(selected);}
 Assert(named,"Name input trigger absent");Assert(route==3?loops>0:complete,"Route failed "+route+" / "+choice);if(route<3)Assert((string)s.variablesState["festival_status"]==(route==2?"friends":"date"),"Unexpected festival route");report.AppendLine("PASS route "+route+", dialogue choice "+choice+", checks "+battles1+"/"+battles2+", lines "+lines);}
 File.WriteAllText("Temp/amora-story-tests.txt",report.ToString());Debug.Log(report.ToString());}
 static void SeekBattle(AmoraGame g){for(int i=0;i<600&&g.Mode!="briefing";i++){if(g.Story.currentChoices.Count>0)g.Choose(0);else g.NextLine();}Assert(g.Mode=="briefing","Battle trigger was not reached");}
 static void RuntimeTests(){var g=AmoraGame.Instance;Assert(g!=null,"Start play mode first");g.NewGame();Assert(g.Mode=="story","New game failed");while(g.Mode=="story")g.NextLine();Assert(g.Mode=="name","Name prompt failed");g.SubmitName("Alex");Assert((string)g.Story.variablesState["playerName"]=="Alex","Name was not bound");SeekBattle(g);g.StartBattle();Assert(g.Mode=="battle","Battle did not start");g.Battle.Paused=true;float t=g.Battle.Elapsed;g.Battle.Tick(1,Vector2.one,true,false);Assert(g.Battle.Elapsed==t,"Pause advanced simulation");g.Battle.Paused=false;var pr=(RectTransform)typeof(AmoraBattle).GetField("player",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).GetValue(g.Battle);float x=pr.anchoredPosition.x;g.Battle.Tick(.05f,Vector2.right,false,false);float normal=pr.anchoredPosition.x-x;x=pr.anchoredPosition.x;g.Battle.Tick(.05f,Vector2.right,false,true);Assert(pr.anchoredPosition.x-x<normal,"Focus did not slow movement");for(int step=0;step<30;step++)g.Battle.Tick(.05f,Vector2.right,false,false);Assert(pr.anchoredPosition.x<=260,"Player escaped arena");g.Battle.TestHit();g.Battle.TestHit();g.Battle.TestHit();Assert(g.Mode=="result"&&!GameData.LastBattle.win,"Loss failed");g.ResolveBattle(false);Assert((int)g.Story.variablesState["fail_count"]==1,"Loss counter not set");SeekBattle(g);g.StartBattle();g.Battle.TestSurvive();Assert(g.Mode=="result"&&GameData.LastBattle.win,"Survival win failed");g.ResolveBattle(true);Assert(g.Mode=="story","Return failed");g.Save();string saved=g.Story.state.ToJson();g.NextLine();g.Load();Assert(saved==g.Story.state.ToJson(),"Save state round trip failed");SeekBattle(g);Assert(g.PendingBattle=="start_bullethell_2","Second trigger failed");g.StartBattle();g.Battle.TestSurvive();g.ResolveBattle(true);for(int i=0;i<300&&g.Mode=="story";i++){if(g.Story.currentChoices.Count>0)g.Choose(0);else g.NextLine();}Assert(g.Mode=="ending","Chapter did not end");Assert((string)g.Story.variablesState["festival_status"]=="date","Date route not selected");g.NewGame();g.SubmitName("Alex");SeekBattle(g);g.StartBattle();for(int step=0;step<650&&g.Mode=="battle";step++){typeof(AmoraBattle).GetField("immune",System.Reflection.BindingFlags.NonPublic|System.Reflection.BindingFlags.Instance).SetValue(g.Battle,100f);g.Battle.Tick(.05f,Vector2.zero,true,false);}Assert(g.Mode=="result"&&GameData.LastBattle.win&&g.Battle.Barrier<=0,"Shooting victory failed");File.WriteAllText("Temp/amora-runtime-tests.txt","PASS name input, event transitions, movement bounds, focus speed, pause, isolated shooting victory, collision loss, retry, survival win, save/load, second check, date ending.");g.ShowTitle();}
 static void Build(){var r=BuildPipeline.BuildPlayer(new BuildPlayerOptions{scenes=new[]{ScenePath},locationPathName="Builds/Amora/CupidBullet.exe",target=BuildTarget.StandaloneWindows64,options=BuildOptions.None});File.WriteAllText("Temp/amora-build.txt",r.summary.result+" errors="+r.summary.totalErrors);}
}
}




